### ISSUE TITLE
Android build fails when using latest RN (0.74)

### ISSUE THREAD

**Issue by gunti96** [bugsnag/bugsnag-js-performance#451] opened 2024-05-14 09:10 UTC
### Describe the bug
1. Just upgraded the project to latest react native version (RN 0.74.1)
2. iOS is okay, but the android build fails with the following error:
```
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installAlphaDebug -PreactNativeDevServerPort=8081
/path/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:62 .parseSync(); ^ TypeError: yargs.option(...).option(...).parseSync is not a function at Object.<anonymous> (/path/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:62:4) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) at node:internal/main/run_main_module:28:49 Node.js v21.1.0 FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':bugsnag_react-native-performance:generateCodegenSchemaFromJavaScript'.
```
3. The project uses many libraries, but if I uninstall just the `@bugsnag/react-native-performance` package, the build works successfully.

### Steps to reproduce
1. Create a bare RN 0.74.1 project
2. `npm install --save @bugsnag/react-native-performance react-native-file-access @react-native-community/netinfo`
3. Try to generate an android build

### Environment
* BugSnag Performance library version: `"@bugsnag/react-native-performance": "^2.5.0"`
* BugSnag Error Monitoring library version (if any): `"@bugsnag/react-native": "^7.22.3"`
* Browser framework version (if any):
    * Vue: -
    * React: 18.2.0
    * Angular: -
* Server framework version (if any):
    * Koa: -
    * Express: -
    * Restify: -
* Browser version (e.g. chrome, safari): -
* Device (e.g. iphonex): android

**Comment by clr182** [comment] 2024-05-21 16:14
Hi @gunti96 

Can you please confirm whether you have enabled [the new architecture option](https://reactnative.dev/docs/the-new-architecture/landing-page) for React-Native 76? 

At present we are seeing issues with this configuration due to changes introduced that alter the native bridge between the JS layer and Android layer when the new architecture option is enabled. We are investigating this issue and will be sure to keep you informed of any updates.

**Comment by gunti96** [comment] 2024-05-22 06:52
Hi @clr182 , thanks for your response.
I can confirm that the new architecture is not enabled for this project.

**Comment by mclack** [comment] 2024-06-05 13:55
Hi @gunti96 

Thanks for your patience here.

After looking through this issue again, I believe there's a chance this is being caused by using an outdated version of the BugSnag React Native SDK. You mention using [v7.22.3](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.22.3), but support for RN 73 was added in [v7.22.4](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.22.4). As you do not have the new architecture enabled and have recently upgraded, I'd assume this is the issue.

Can you confirm whether you were using a RN version below 73 prior to this upgrade? Are you able to upgrade to a newer version of `@bugsnag/react-native` and let us know whether this fixes the issue?

**Comment by gunti96** [comment] 2024-06-06 07:58
Hi @mclack 

Thanks for your response.
Just tried with the latest versions:
```
    "@bugsnag/react-native": "^7.23.0",
    "@bugsnag/react-native-performance": "^2.6.0",
```
and unfortunately similar error is thrown for the android build:
```
/path/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:62
  .parseSync();
   ^

TypeError: yargs.option(...).option(...).parseSync is not a function
    at Object.<anonymous> (/path/node_modules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:62:4)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v21.1.0
```

As mentioned above, if I just uninstall the performance library then the build succeeds

**Comment by mclack** [comment] 2024-06-14 15:30
Hi @gunti96 

Thanks for sharing that with us.

We've added a task to our backlog to investigate this issue further. We'll make sure to post any updates on this thread.

**Comment by yousif-bugsnag** [comment] 2024-06-21 09:18
Hi @gunti96,

We haven't been able to reproduce this on a fresh 0.74 project, either on old or new architecture.

It seems like this is an issue with codegen and yargs, and not just related to BugSnag - please see https://github.com/expo/expo/issues/28494#issuecomment-2081770811

**Comment by yousif-bugsnag** [comment] 2024-06-21 14:01
I'm going to close this as I don't think it's an issue with `@bugsnag/react-native-performance` - but if the linked solution above doesn't work and you're able to provide a reproduction example then we'd be happy to reopen and try to investigate further.

**Closed by yousif-bugsnag** 2024-06-21 14:01 UTC

**Comment by gunti96** [comment] 2024-06-25 10:33
Hi @yousif-bugsnag,
It seems that the linked solution doesn't work after a fresh install, but will try to investigate more in-depth and maybe provide an example if possible.
